### ISSUE TITLE
Volunteers can specify their favorite categories

### ISSUE THREAD

**Issue by AbuJabal-Hussein** [haitham-kablan/HadarSocialNetwork#54]
- change the volunteer feed to view help requests of his favorite categories first
- when registering in the app, the volunteer have to choose the help request categories that he is willing to help with

**Comment by elazarg** [comment]
I'd expect this to be controlled from a "preferences" tab.

**Comment by AbuJabal-Hussein** [comment]
> 
> 
> I'd expect this to be controlled from a "preferences" tab.

Yes, I think we should do this in addition to specifying the categories in the registration phase.

**Comment by elazarg** [comment]
So I guess you can transfer the registering user to the preferences page.
